/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// AdmissionFairSharingApplyConfiguration represents a declarative configuration of the AdmissionFairSharing type for use
// with apply.
//
// AdmissionFairSharing contains the properties of the ClusterQueue
// when participating in AdmissionFairSharing.
type AdmissionFairSharingApplyConfiguration struct {
	// mode indicates which mode for AdmissionFairSharing should be used.
	// Possible values are:
	// - UsageBasedAdmissionFairSharing
	// - NoAdmissionFairSharing
	Mode *kueuev1beta2.AdmissionMode `json:"mode,omitempty"`
}

// AdmissionFairSharingApplyConfiguration constructs a declarative configuration of the AdmissionFairSharing type for use with
// apply.
func AdmissionFairSharing() *AdmissionFairSharingApplyConfiguration {
	return &AdmissionFairSharingApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *AdmissionFairSharingApplyConfiguration) WithMode(value kueuev1beta2.AdmissionMode) *AdmissionFairSharingApplyConfiguration {
	b.Mode = &value
	return b
}
